### ISSUE TITLE
Tooltips on amounts?

### ISSUE THREAD

**Issue by ayman** [andreasg123/covid-plot#2]
It would be nice to have a hover tooltip on the amounts in the graph.  It's too hard to eyeball.

<img width="290" alt="image" src="https://user-images.githubusercontent.com/1846/87840665-b6a0fa80-c855-11ea-9b77-039d7db4d3da.png">

**Comment by yulius-fxpal** [comment]
Implemented in PR#4
https://github.com/andreasg123/covid-plot/pull/4
